### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by Enternal-w** [YhuoyuH/RetinexMamba#9]
在test过程中出现ValueError: axes don't match array问题

具体如下
2024-07-02 11:17:26,195 INFO: Dataset Dataset_PairedImage - TrainSet is created.
2024-07-02 11:17:26,196 INFO: Number of test images in TrainSet: 485
2024-07-02 11:17:26,197 INFO: Dataset Dataset_PairedImage - ValSet is created.
2024-07-02 11:17:26,197 INFO: Number of test images in ValSet: 15
Disable distributed.
Not using Automatic Mixed Precision
2024-07-02 11:17:27,391 INFO: Model [ImageCleanModel] is created.
2024-07-02 11:17:27,392 INFO: Testing TrainSet...
Traceback (most recent call last):
  File "/home/jia/RetinexMamba-main/basicsr/test.py", line 62, in <module>
    main()
  File "/home/jia/RetinexMamba-main/basicsr/test.py", line 53, in main
    model.validation(
  File "/home/jia/RetinexMamba-main/basicsr/models/base_model.py", line 51, in validation
    return self.nondist_validation(dataloader, current_iter, tb_logger,
  File "/home/jia/RetinexMamba-main/basicsr/models/image_restoration_model.py", line 310, in nondist_validation
    self.metric_results[name] += getattr(
  File "/home/jia/RetinexMamba-main/basicsr/metrics/psnr_ssim.py", line 40, in calculate_psnr
    img1 = img1.detach().cpu().numpy().transpose(1,2,0)
ValueError: axes don't match array

**Comment by YhuoyuH** [comment]
了解您的问题，感谢您对我们工作的关注



发自我的iPhone


------------------ Original ------------------
From: Enternal-w ***@***.***&gt;
Date: Tue,Jul 2,2024 11:24 AM
To: YhuoyuH/RetinexMamba ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [YhuoyuH/RetinexMamba] ValueError: axes don't match array (Issue #9)





 
在test过程中出现ValueError: axes don't match array问题
 
具体如下
 2024-07-02 11:17:26,195 INFO: Dataset Dataset_PairedImage - TrainSet is created.
 2024-07-02 11:17:26,196 INFO: Number of test images in TrainSet: 485
 2024-07-02 11:17:26,197 INFO: Dataset Dataset_PairedImage - ValSet is created.
 2024-07-02 11:17:26,197 INFO: Number of test images in ValSet: 15
 Disable distributed.
 Not using Automatic Mixed Precision
 2024-07-02 11:17:27,391 INFO: Model [ImageCleanModel] is created.
 2024-07-02 11:17:27,392 INFO: Testing TrainSet...
 Traceback (most recent call last):
 File "/home/jia/RetinexMamba-main/basicsr/test.py", line 62, in 
 main()
 File "/home/jia/RetinexMamba-main/basicsr/test.py", line 53, in main
 model.validation(
 File "/home/jia/RetinexMamba-main/basicsr/models/base_model.py", line 51, in validation
 return self.nondist_validation(dataloader, current_iter, tb_logger,
 File "/home/jia/RetinexMamba-main/basicsr/models/image_restoration_model.py", line 310, in nondist_validation
 self.metric_results[name] += getattr(
 File "/home/jia/RetinexMamba-main/basicsr/metrics/psnr_ssim.py", line 40, in calculate_psnr
 img1 = img1.detach().cpu().numpy().transpose(1,2,0)
 ValueError: axes don't match array
